<?php
/**
 * 授权基类，所有获取access_token以及验证access_token 异常都在此类中完成
 */

namespace app\api\controller;

use app\api\model\Identity;
use app\api\model\Member;
use app\common\model\Share;
use think\Controller;
use think\Db;
use think\Request;
use think\Session;



header("Access-Control-Allow-Origin:*");
class Api extends Controller
{
    public  $noCheck = [
        'register','login','gettoken','wxnotify','wxlogin'
    ];//跳过登录token验证
    public $uid;
    const PAY = 0;

    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        //当前方法
        $action = Request::instance()->action();
        if(!in_array($action,$this->noCheck)){
            self::checkUid();
            $accessToken = isset($_SERVER['HTTP_ACCESSTOKEN'])?$_SERVER['HTTP_ACCESSTOKEN']:'';
            $uid = session('uid');
            Token::checkAccessToken($accessToken,$uid);
        }
    }
    protected  function checkUid(){
        $uid = session('uid');
        if(!$uid){
            Share::jsonData(100,'','你还没登录');
        }
        $loginTime = session('login');
        $now = time();
        $expire = 7200;
        if(($loginTime + $expire) < $now ){
            session(null);//销毁所有登录信息
            Share::jsonData(101,'','登录失效，请重新登录！');
        }
        $this->uid = $uid;
    }
    //TODO 微信授权登录
    public function wxLogin() {
//            $json = '{"nickname":".","openid":"o8m6C57HIDfgizWst5ORVxyAXjfI","unionid":"oTa415y5Xs0rTBmN20ngPoEuSMFg","headimgurl":"http://thirdwx.qlogo.cn/mmopen/vi_32/SkxPZKY0iboCkjbtGXic5oYmFAJNnS1UjiaGs2rGfZutA1FZydUAKl2h7cVGfCtYX50SibbOugJzUgsZQuvQvlhbtw/132"}';
//            $str = json_decode($json,true);
        $name = strip_tags(input('nickname'));//昵称
        $openid = strip_tags(input('openid')); //openid
        $unionid = strip_tags(input('unionid'));
        $phone = ""; // 手机号码
        $password = "123456"; // 密码
        $headimg = strip_tags(input('headimgurl'));
//			$headimg = $str['headimgurl'];
        if($headimg=='')$headimg ='/mr.jpg';
        Share::checkEmptyParams(['openid'=>$openid,'nickname'=>$name]);
        $user = db('member')->where('openid',$openid)->find();
        if(!$user){//修改
            $params = [
                'phone'=>$phone,
                'password'=>md5($password),
                'real_pass'=>$password,
                'username'=>$name,
                'nickname'=>$name,
                'createTime'=>time(),
                'money'=>0,
                'openid'=>$openid,
                'unionid'=>$unionid,
                'avatar'=>$headimg,
            ];
            $res = db('member')->insert($params);
        }else{//新增
            $params = [
                'phone'=>$phone,
                'password'=>md5($password),
                'real_pass'=>$password,
                'nickname'=>$name,
                'unionid'=>$unionid,
                'createTime'=>time(),
            ];
            $res = db('member')->where('openid',$openid)->update($params);
        }
        if($res){//登录成功
            $user = db('member')->where('openid',$openid)->find();
            session('uid',$user['id']);
            session('login',time());
            Share::jsonData(1,$user,'登录成功');
        }else{
            Share::jsonData(0,'','授权失败！');
        }

    }


    /**
     * 获取token
     */
    public function getToken(){
        Token::setAccessToken();
    }
    /**
     * 头像上传
     */
    public function uploadImg(){
        $host = config('hostUrl');
        $file = request()->file('file');
        $type = input('type',1);//1-头像  2-商品图片
        if (!empty($file)) {
            // 移动到框架应用根目录/public/uploads/category 目录下
            if($type ==1){
                $info = $file->move(ROOT_PATH . 'public' . DS . 'uploads/avatar');
                $dir = '/uploads/avatar';
            }else{
                $info = $file->move(ROOT_PATH . 'public' . DS . 'uploads/product');
                $dir = '/uploads/product';
            }
            if ($info) {
                $src = $dir . '/' . date('Ymd') . '/' . $info->getFilename();
                Share::jsonData(0,['src' => $src]);
            } else {
                // 上传失败获取错误信息
                Share::jsonData(0,'',$file->getError());
            }
        }else{
            Share::jsonData(0,'','图片不存在');
        }
    }
    /**
     * 文件上传
     */
    public function uploadFile(){
        $host = config('hostUrl');
        $file = request()->file('file');
        if (!empty($file)) {
            // 移动到框架应用根目录/public/uploads/category 目录下
            $info = $file->move(ROOT_PATH . 'public' . DS . 'uploads/file');
            if ($info) {
                $src = '/uploads/file' . '/' . date('Ymd') . '/' . $info->getFilename();
                Share::jsonData(1,['src' => $src]);
            } else {
                // 上传失败获取错误信息
                Share::jsonData(0,'',$file->getError());
            }
        }else{
            Share::jsonData(0,'','文件不存在');
        }
    }

}